src/core/models.py
from datetime import datetime

from src import db


class UserSubmission(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    subject = db.Column(db.String(120), nullable=False)
    submission = db.Column(db.String(1000), nullable=False)
    created_on = db.Column(db.DateTime, nullable=False, server_default=db.func.now())
    filename = db.Column(db.String(250), nullable=True)
    contact = db.Column(db.String(250), nullable=False)
    

    def __init__(self, user_id, submission, contact, subject, filename=None, ):
        self.user_id = user_id
        self.subject = subject
        self.submission = submission
        self.filename = filename
        self.created_on = datetime.now()
        self.contact = contact

src/core/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed

from wtforms import StringField, SubmitField, TextAreaField, FileField, SelectField
from wtforms.validators import InputRequired, Length, ValidationError, Regexp, EqualTo


class SubmissionForm(FlaskForm):
    subject = StringField('Subject', validators=[InputRequired(), Length(min=4, max=80)], render_kw={"placeholder": "Subject"})
    contact_option = SelectField('Contact Option', choices=[('email', 'Email'), ('phone', 'Phone')], validators=[InputRequired()])
    submission = TextAreaField('Submission', 
                validators=[InputRequired(), Length(min=4, max=1000)], 
                render_kw={"placeholder": "Submission"})
    image = FileField('Image', 
                validators=[InputRequired(), 
                            FileAllowed(['jpg', 'png', 'jpeg'], '.jpg, .png, .jpeg files only!')],
                render_kw={"placeholder": "Image"})
    submit = SubmitField('Submit')

src/__init__.py
from decouple import config
import os
from cryptography.fernet import Fernet

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_mail import Mail
from flask_security import Security, SQLAlchemyUserDatastore



app = Flask(__name__)
app_settings_value = os.environ.get('APP_SETTINGS')

app.config.from_object(app_settings_value)

# print(app.config)

cipher_suite = Fernet(config("ENCRYPTION_KEY"))


login_manager = LoginManager()
login_manager.init_app(app)

db = SQLAlchemy(app)



bcrypt = Bcrypt(app)
migrate = Migrate(app, db)
mail = Mail(app)

from src.accounts.views import accounts_bp
from src.core.views import core_bp
#inspect(accounts_bp, title="accounts_bp")
app.register_blueprint(accounts_bp)
app.register_blueprint(core_bp)




login_manager.login_view = 'accounts.login'
login_manager.login_message_category = 'danger'


from src.accounts.models import User, Role

user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()




########################
#### error handlers ####
########################


@app.errorhandler(401)
def unauthorized_page(error):
    return render_template("errors/401.html"), 401


@app.errorhandler(404)
def page_not_found(error):
    return render_template("errors/404.html"), 404


@app.errorhandler(500)
def server_error_page(error):
    return render_template("errors/500.html"), 500

src/accounts/views.py
from datetime import datetime
import requests
from rich import inspect

from flask import Blueprint, render_template, redirect, url_for, flash, current_app, request
from flask_login import login_required, current_user, logout_user, login_user

from src import bcrypt, db, cipher_suite

from src.accounts.forms import ChangePasswordForm, ResetForgotPasswordForm, RegisterForm, LoginForm, TwoFactorForm, ForgotPasswordForm
from src.accounts.models import User, PasswordChanges, encrypt_data, decrypt_data
from src.utils.decorators import logout_required
from src.utils.email import send_email
from src.utils.two_factor import getb64encoded_qr_image
from src.accounts.token import generate_token, confirm_token

accounts_bp = Blueprint('accounts', __name__, template_folder='templates/accounts/')

@accounts_bp.route('/login', methods=['GET', 'POST'])
@logout_required
def login():
    if current_user.is_authenticated:
        if current_user.is_two_factor_authentication_enabled:
            flash("You are already logged in.", "info")
            return redirect(url_for('core.app'))
        else:
            flash("You have not enabled 2-Factor Authentication. Please enable first to login.", "info")
            return redirect(url_for('accounts.two_factor_setup'))

    form = LoginForm()

    if form.validate_on_submit():
        users = User.query.all()
        # Loop through the users and print the _email values
        for user in users:
            # print(user.email)
            if user.email == form.email.data:
   
                if bcrypt.check_password_hash(user.password, form.password.data):
                    login_user(user)
                    if not current_user.is_two_factor_enabled:
                        flash("You have not enabled 2-Factor Authentication. Please enable first to login.", "info")
                        return redirect(url_for('accounts.two_factor_setup'))
                    return redirect(url_for('accounts.two_factor_verify'))
                else:
                    flash('Invalid username or password', 'danger')
        else:
            flash('Invalid username or password', 'danger')
    
    return render_template('/accounts/login.html', form=form)


def authenticate_recaptcha(form):
    secret_response = request.form.get('g-recaptcha-response')
    verify_response = requests.post(url =f'{current_app.config["RECAPTCHA_VERIFY_URL"]}?secret={current_app.config["RECAPTCHA3_PRIVATE_KEY"]}&response={secret_response}')
    
    print(verify_response.json())
    
    if verify_response.json()['success']:
        return True
    else:
        return False


@accounts_bp.route('/register', methods=['GET', 'POST'])
@logout_required
def register():
    if current_user.is_authenticated:
        if current_user.is_two_factor_enabled:
            flash('You have already enabled two factor authentication.', 'success')
            return redirect(url_for('core.app'))
        else:
            flash('You must have 2-Factor Authentication enabled before you can access the site', 'warning')
            return redirect(url_for('accounts.two_factor_setup'))
    
    
    form = RegisterForm()
    
    if form.validate_on_submit():

        try:
            if not authenticate_recaptcha(form):
                flash('Please check the captcha', 'danger')
                return redirect(url_for('accounts.register'))
            inspect(form)
            user = User(
                email=form.email.data,
                password=form.password.data,
                phone=form.phone.data,
                name=form.name.data
            )
            # inspect(user)
            db.session.add(user)
            db.session.commit()

            token = generate_token(user.email)
            confirm_url = url_for('accounts.confirm_email', token=token, _external=True)
            html = render_template('/accounts/confirm_email.html', confirm_url=confirm_url)
            subject = "Welcome to Lovejoy's Antique Evaluations! Confirm your email"
            send_email(user.email, subject, html)

            login_user(user)
            flash('A confirmation email has been sent via email.', 'success')
        
            return redirect(url_for('accounts.inactive'))
        except Exception as e:
            db.session.rollback()
            print(e)
            flash('There was a problem creating your account.', 'danger')


    return render_template('/accounts/register.html', form=form, reCAPTCHA_site_key = current_app.config['RECAPTCHA3_PUBLIC_KEY'])

@accounts_bp.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash('Account already confirmed. Please login.', 'success')
        return redirect(url_for('core.app'))
    email = confirm_token(token)
    # print(email)
    # print(current_user._email)
    # print(encrypt_data(email))
    # print(current_user.email == email)
    # print(current_user._email == encrypt_data(email))

    try:

    # Perform actions with the user object as needed
    # except Exception as e:
        # Handle the case where no user is found
        users = User.query.all()
        # Loop through the users and print the _email values
        for user in users:
            # print(user.email)
            if user.email == email:
                # print('HERE')
                user.is_confirmed = True
                user.confirmed_on = datetime.now()
                db.session.add(user)
                db.session.commit()
                flash('You have confirmed your account. Thanks!', 'success')
        print("User not found.")
    # user = User.query.filter_by(email=email).first_or_404()
    # if user.email == email:
    #     user.is_confirmed = True
    #     user.confirmed_on = datetime.now()
    #     db.session.add(user)
    #     db.session.commit()
    #     flash('You have confirmed your account. Thanks!', 'success')   
    except Exception as e:
        flash('The confirmation link is invalid or has expired.', 'danger')
    return redirect(url_for('core.app'))

@accounts_bp.route('/inactive')
@login_required
def inactive():
    if current_user.is_confirmed and current_user.is_two_factor_enabled:
        return redirect(url_for('core.app'))
    elif current_user.is_confirmed and not current_user.is_two_factor_enabled:
        flash('Please enable two factor authentication.', 'warning')
        return redirect(url_for('accounts.two_factor_setup'))
    else:
        flash('Please confirm your account!', 'warning')
        return render_template('/accounts/inactive.html')

@accounts_bp.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('accounts.login'))
                    

@accounts_bp.route('/resend')
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash('Your account has already been confirmed.', 'success')
        return redirect(url_for('core.home'))
    token = generate_token(current_user.email)
    confirm_url = url_for('accounts.confirm_email', token=token, _external=True)
    html = render_template('/accounts/confirm_email.html', confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('accounts.inactive'))


@accounts_bp.route('/two_factor_setup', methods=['GET', 'POST'])
@login_required
def two_factor_setup():
    if current_user.is_two_factor_enabled:
        flash('Two factor authentication is already enabled for your account.', 'success')
        return redirect(url_for('core.app'))
    secret = current_user.secret_token
    uri = current_user.get_auth_uri()
    base64_qr_image = getb64encoded_qr_image(uri)
    return render_template('/accounts/two_factor_setup.html', secret=secret, qr=base64_qr_image)

@accounts_bp.route('/two_factor_verify', methods=['GET', 'POST'])
@login_required
def two_factor_verify():
    form = TwoFactorForm(request.form)
    if form.validate_on_submit():
        if current_user.verify_totp(form.otp.data):
            if current_user.is_two_factor_enabled:
                flash('Two factor authentication is already enabled for your account.', 'success')
                return redirect(url_for('core.app'))
            else:
                try:
                    print('HERE')
                    current_user.is_two_factor_enabled = True
                    db.session.commit()
                    flash('Two factor authentication has been enabled.', 'success')
                    return redirect(url_for('core.app'))
                except Exception as e:
                    db.session.rollback()
                    flash('There was a problem enabling two factor authentication.', 'danger')
                    return redirect(url_for('accounts.two_factor_verify'))
        else:
            flash('Invalid OTP. Please try again.', 'danger')
            return redirect(url_for('accounts.two_factor_verify'))
    # else:
    #     if not current_user.is_two_factor_enabled:
    #         flash('You must have 2-Factor Authentication enabled before you can access the site', 'warning')
    #         return redirect(url_for('accounts.two_factor_setup'))
    
    return render_template('/accounts/two_factor_verify.html', form=form)

@accounts_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    return render_template('/accounts/settings.html')


@accounts_bp.route('/settings/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        if bcrypt.check_password_hash(current_user.password, form.current_password.data):
            current_user.password = bcrypt.generate_password_hash(form.new_password.data)
            db.session.add(current_user)
            db.session.commit()

src/core/views.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename


import uuid
from rich import inspect

from src import db
from src.core.forms import SubmissionForm
from src.core.models import UserSubmission
from src.accounts.models import User
from src.utils.decorators import email_verification_required, check_is_2fa_enabled
from src.utils.image import is_valid_image, is_less_than_max_file_size

core_bp = Blueprint('core', __name__, template_folder='templates/core')

@core_bp.route('/')
def home():
    return render_template('core/index.html')


@core_bp.route('/app')
@login_required
@email_verification_required
@check_is_2fa_enabled
def app():
    form = SubmissionForm()
    if current_user.is_authenticated:
        user_submissions = UserSubmission.query.filter_by(user_id=current_user.id).all()
        return render_template('core/dashboard.html', user_submissions=user_submissions, form=form)

    return render_template('core/dashboard.html', form=form)


@core_bp.route('/admin-dashboard')
@login_required
def admin_dashboard():
    user_submissions = UserSubmission.query.all()
    submissions_with_user_info = []

    for submission in user_submissions:
        user_info = next((user for user in User.query.all() if user.id == submission.user_id), None)
        if user_info:
      
            submissions_with_user_info.append({
                'subject': submission.subject,
                'content': submission.submission,
                'filename': submission.filename,
                'created_on': submission.created_on,
                'user_name': user_info.name,
                'user_email': user_info.email,
                'user_phone': user_info.phone,
                'contact': submission.contact
            })
    sorted_submissions = sorted(submissions_with_user_info, key=lambda k: k['created_on'], reverse=True)
    if not current_user.is_admin:
        flash('You are not authorized to access this page.', 'danger')
        return redirect(url_for('core.home'))
    return render_template('core/admin_dashboard.html', user_submissions=sorted_submissions)

@core_bp.route('/submission', methods=['POST'])
@login_required
@email_verification_required
@check_is_2fa_enabled
def submission():
    form = SubmissionForm()
    
    if form.validate_on_submit():
        inspect(form.image.data)
        image = form.image.data

        if not is_valid_image(image):
            flash('Invalid file type. Only jpg, jpeg, and png files are allowed.', 'danger')
        elif not is_less_than_max_file_size(image):
            flash('File size is too large. Max file size is 5MB.', 'danger')
        else:
            filename =  str(uuid.uuid4()) + '-' + secure_filename(form.image.data.filename) 
            inspect(form.image.data)
            file = request.files['image']
            
            file.save(current_app.config['UPLOAD_FOLDER'] + filename)

            # img = Image.open(form.image.data)
            # img.show()

            user_submission = UserSubmission(user_id=current_user.id, subject=form.subject.data, submission=form.submission.data, filename=filename, contact=form.contact_option.data)
            db.session.add(user_submission)
            db.session.commit()
            flash('Your submission has been saved.', 'success')
            return redirect(url_for('core.app'))
    return render_template('core/dashboard.html', form=form)

src/templates/core/admin_dashboard.html
{% extends "_base.html" %}
{% block content %}


<div class="container mt-5">
    <div class="row">
        {% for submission in user_submissions %}
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <img src="{{ url_for('static', filename='uploads/' + submission.filename) }}" alt="Thumbnail" class="card-img">
                    </div>
                    <div class="col-md-8">
                        <div class="card-text">
                            <h5 class="card-title">{{ submission.subject }}</h5>
                            <p> {{ submission.created_on }}</p>
                            {% if submission.contact == 'phone' %}
                            <p>
                                <a href="tel:{{ submission.user_phone }}">
                                    Call
                                </a>
                            <p>
                            {% endif %}
                            {% if submission.contact == 'email' %}
                                <a href="mailto:{{ submission.user_email }}?subject={{ submission.subject }}">
                                    Send Email
                                </a>
                            </p>
                            {% endif %}
                            <p>{{ submission.user_name}}</p>
                            <p>{{ submission.content }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

src/templates/core/dashboard.html
{% extends "_base.html" %}
{% block content %}

<main>
<div>
    <h1 class="text-center">Evaluation Dashboard</h1>
    <p class="text-center">Welcome {{current_user.name}}! Use the form below to request an evaluation.</p>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6">
                {% if user_submissions %}
                    <div id="previous-uploads">
                        {% for submission in user_submissions %}
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img src="{{ url_for('static', filename='uploads/' + submission.filename) }}" alt="Thumbnail" class="card-img">
                                        </div>
                                        <div class="col-md-8">
                                            <div class="card-text">
                                                <h5 class="card-title">{{ submission.subject }}</h5>
                                                <p>{{ submission.submission }}</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                <div class="alert alert-info" role="alert">
                    No previous uploads.
                </div>
                {% endif %}
            </div>

            <div class="col-md-6">
                <form action="{{ url_for('core.submission') }}" method="post" enctype="multipart/form-data">

                    <div class="form-floating">
                        {{ form.subject(placeholder="Subject", class="form-control mb-2") }}
                        {{ form.subject.label }}
                          {% if form.subject.errors %}
                            {% for error in form.subject.errors %}
                              <div class="alert alert-danger" role="alert">
                                {{ error }}
                              </div>
                            {% endfor %}
                          {% endif %}
                      </div>
                      <div class="form-floating">
                        {{ form.contact_option(placeholder="contact option", class="form-control mb-2") }}
                        {{ form.contact_option.label }}
                          {% if form.contact_option.errors %}
                            {% for error in form.contact_option.errors %}
                              <div class="alert alert-danger" role="alert">
                                {{ error }}
                              </div>
                            {% endfor %}
                          {% endif %}
                      </div>
                      <div class="form-floating">
                        {{ form.submission(placeholder="description", class="form-control mb-2") }}
                        {{ form.submission.label }}
                          {% if form.submission.errors %}
                            {% for error in form.submission.errors %}
                              <div class="alert alert-danger" role="alert">
                                {{ error }}
                              </div>
                            {% endfor %}
                          {% endif %}
                      </div>
                      <div class="form-control-file">
                        {{ form.image(placeholder="upload image", class="form-control mb-2") }}
                        <!-- {{ form.image.label }} -->
                          {% if form.image.errors %}
                            {% for error in form.image.errors %}
                              <div class="alert alert-danger" role="alert">
                                {{ error }}
                              </div>
                            {% endfor %}
                          {% endif %}
                      </div>

                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>
            </div>
        </div>
    </div>

</div>
</main>
{% endblock %}

src/templates/core/index.html
{% extends "_base.html" %}
{% block content %}

<h1 class="text-center">Welcome {{current_user.email}}!</h1>

{% endblock %}